### ISSUE TITLE
Support the V2 Neo

### ISSUE THREAD

**Issue by adrianocr** [CrealityOfficial/Ender-3V2#1]
It would be great if this repo could also add support for the V2 Neo or if a separate repo could be opened for the V2 Neo

At the very least if the correct Marlin configs were provided that would be great and we could build the rest ourselves based on the upstream Marlin repo

**Comment by CrealityTech** [comment]
We have plan to public Ender3-v2 Neo project ,coming soon;

**Comment by adrianocr** [comment]
@CrealityTech thank you very much for the reply.

Is there a rough timeline by any chance? Something like Q4 2022 or Q1 2023?

Additionally can you guys please provide information/support on how the new DACAI screens are able to render the preview? It seems that the information is not publicly available so third-party firmwares have no idea how to generate the thumbnail previews for DACAI screens in slicers like Cura and PrusaSlicer.

**Comment by CrealityTech** [comment]
> @CrealityTech thank you very much for the reply.
> 
> Is there a rough timeline by any chance? Something like Q4 2022 or Q1 2023?
> 
> Additionally can you guys please provide information/support on how the new DACAI screens are able to render the preview? It seems that the information is not publicly available so third-party firmwares have no idea how to generate the thumbnail previews for DACAI screens in slicers like Cura and PrusaSlicer.

we will test Cura and PrusaSlicer and publish

**Comment by rcarteraz** [comment]
Any update on this?

**Comment by breunouddanedeu** [comment]
> We have plan to public Ender3-v2 Neo project ,coming soon;
> we will test Cura and PrusaSlicer and publish

Any news on this subject ? The issue is closed but I can't fin the repo.

**Comment by Natgho** [comment]
Me too!!!
