### ISSUE TITLE
DACAI screen firmware source code

### ISSUE THREAD

**Issue by NiLMoXiE** [CrealityOfficial/Ender-3V2#2]
Could you please publish the source code for the newer DACAI type screen and the API, so that it can be enabled for gcode preview? 

It works on Ender3v2 with older DWIN screens.

**Comment by CrealityTech** [comment]
> 

it's compatliable

**Comment by NiLMoXiE** [comment]
Can you tell me what API to use??

**Comment by NiLMoXiE** [comment]
How is this closed - "it's compatible" is not an answer - It may well be compatible but it doesn't work! And as Creality haven't released the source code for the newer DACAI screens so we can't find out what API it uses to make it work.

Please provide source code for DACAI type screen firmware.(firmware.zlib)
